config/routes.rb
Rails.application.routes.draw do
  get 'orders/:id/pay', to:'orders#pay', as:'order_pay'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'products#index'
  resources :products
  resources :orders
  resources :order_products

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products, dependent: :destroy

  def update_price
    total_price = order_products.sum(:total_price)
    update(price: total_price)
  end

  def process_payment(token, email)
    customer = Stripe::Customer.create email: email,
                                       card: token

    Stripe::Charge.create customer: customer.id,
                          amount: (price * 100).to_i,
                          description: 'Produit',
                          currency: 'eur'

  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :user
  belongs_to :order
  
  before_save :set_price
  after_save :update_order

  delegate :price, :name, to: :product

  def set_price
    self.unit_price = product.price
    self.total_price = product.price * quantity
  end

  def update_order
    order.update_price
  end

end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController

  def create
    @order_product = current_user.order_products.find_or_initialize_by(order_product_params)
    set_quantity
    set_order
    redirect_to @order_product if @order_product.save!
  end

  def show
    @order_product = current_user.order_products.find_by(id: params[:id])
  end

  private

    def set_quantity
      @order_product.quantity = @order_product.persisted? ? @order_product.quantity + 1 : 1
    end

    def set_order
      current_order = current_user.orders.find_by(paid: false)
      unless current_order.present?
        current_order = @order_product.build_order
        current_order.save!
      end
      @order_product.order = current_order
    end

    def order_product_params
      params.require(:order_product).permit(:product_id)
    end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :pay, :update]

  def show
  end

  def edit

  end

  def pay

  end

  def update
    @order.process_payment(stripe_params[:stripeToken], stripe_params[:stripeEmail])
    @order.save
    redirect_to @order, notice: 'Order was successfully paid.'
  end

  private
    def set_order
      @order= current_user.orders.find_by(id: params[:id], paid: false)
    end

  def stripe_params
    params.permit :stripeEmail, :stripeToken
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = Product.all
  end

  def show
    # @product = Product.where(id: params[:id]).first
    @product = Product.find_by(id: params[:id])
    @order_product = OrderProduct.new()
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_products_helper.rb
module OrderProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <% if user_signed_in? %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-brand" %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          Signed in as <%= current_user.email %>
        </li>

        <li class="nav-item nav-link">
          <%= link_to "produits", products_path %>
        </li>
      </ul>
    </div>
  <%end%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/order_products/_recap.html.erb
<div class="card" style="width: 18rem;">
  <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
  <div class="card-body">
    <h5 class="card-title"><%= order_product.name %></h5>
    <%= order_product.quantity %> * PU : <%= number_to_currency(order_product.unit_price) %>
    <span class="btn btn-primary"><%= number_to_currency(order_product.total_price) %></span>
  </div>
</div>

app/views/order_products/show.html.erb
<%= @order_product.id %>
Quantité : <%= @order_product.quantity %>

<%= link_to "Procéder au paiement", @order_product.order, class: "btn btn-primary" %>

app/views/orders/edit.html.erb
<%= @order.price %>
<%= @order.paid %>
<% @order.order_products.each do |order_product| %>
  <%= render partial: 'order_products/recap.html.erb', locals: {order_product: order_product} %>
<% end %>

<%= link_to "confirmer le paiement", order_pay_path %>

app/views/orders/pay.html.erb
form de paiement :

<%= form_for @order, html: { class: "basic-grey" } do |f| %>
  <div class="actions">
    <script
      src="https://checkout.stripe.com/checkout.js"
      class="stripe-button"
      data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
      data-name="Demo Site"
      data-description="2 widgets ($20.00)"
      data-amount="<%= @order.price * 100 %>">
    </script>
  </div>
<% end %>

app/views/orders/show.html.erb
montant : <%= number_to_currency(@order.price) %>
<hr>
<% if @order.paid %>
  déjà réglé
<% else %>
  <%= link_to "payer", edit_order_path %>
<% end %>

app/views/products/index.html.erb
<% @products.each do |product| %>
  <div class="card" style="width: 18rem;">
    <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
    <div class="card-body">
      <h5 class="card-title"><%= link_to product.name, product %></h5>
      <p class="card-text">  <%= product.description %></p>
      <span class="btn btn-primary"><%= number_to_currency(product.price) %></span>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
Notre produit

<%= @product.name %>
<br>
<%= @product.description %>
<br>
<%= @product.price %>


<%= form_for @order_product do |f| %>
  <%= f.hidden_field :product_id, value: @product.id %>
  <%= f.submit "Ajouter au pannier" %>
<% end %>